// Xkiro exposes an OpenAI-compatible model-discovery endpoint (GET /v1/models),
// so models are normally registered dynamically at startup. This list is only
// used as a manual fallback when the live /models endpoint is unavailable.
export const MODELS: string[] = [
  "qwen/qwen3-vl-plus:free",
  "openai/gpt-5.3-codex-spark",
  "minimax/minimax-m2.7:free",
  "minimax/minimax-m2.7-highspeed:free",
  "minimax/minimax-m2.5:free",
  "minimax/minimax-m3:free",
  "minimax/minimax-m2.1-highspeed:free",
  "minimax/minimax-m2.5-highspeed:free",
  "minimax/minimax-m2.1:free",
  "minimax/minimax-m2:free",
  "qwen/qwen3.5-flash:free",
  "qwen/qwen3.6-plus:free",
  "qwen/qwen3.5-397b-a17b:free",
  "qwen/qwen3.5-omni-flash:free",
  "qwen/qwen3.6-max-preview:free",
  "qwen/qwen3.5-plus:free",
  "qwen/qwen3.5-omni-plus:free",
  "qwen/qwen3.8-max:free",
  "qwen/qwen3.7-max:free",
  "qwen/qwen3.6-27b:free",
  "qwen/qwen3.6-35b-a3b:free",
  "qwen/qwen3-max:free",
  "qwen/qwen3-coder-plus:free",
  "qwen/qwen3.7-plus:free",
  "qwen/qwen-plus-2025-07-28:free",
  "qwen/qwen3-omni-flash:free",
  "qwen/qwen3.8-max:free",
  "deepseek/deepseek-v4-pro",
  "deepseek/deepseek-v3.2",
  "deepseek/deepseek-chat-v3.1",
  "deepseek/deepseek-v4-flash",
  "sensenova/sensenova-6.8-flash-lite",
  "sensenova/sensenova-6.7-flash-lite",
  "mistralai/mistral-large-2512",
  "mistralai/mistral-medium-3.5",
  "mistralai/mistral-small-2603",
  "mistralai/codestral-2508",
  "mistralai/devstral-medium",
  "mistralai/ministral-8b",
  "mistralai/ministral-14b",
  "mistralai/ministral-3b",
];
