// TokenRouter exposes an OpenAI-compatible model-discovery endpoint (GET /v1/models),
// so models are normally registered dynamically at startup. This list is only
// used as a manual fallback when the live /models endpoint is unavailable
// (network error, WAF block, or a key that lacks /models access). It mirrors the
// well-known catalog TokenRouter serves so the provider stays routable.
export const MODELS: string[] = [
  'deepseek/deepseek-v4-pro',
  'deepseek/deepseek-v4-pro-0813',
  'deepseek/deepseek-v4-pro-0813-free',
  'deepseek/deepseek-v4-flash',
  'deepseek/deepseek-v4-flash-0731',
  'deepseek/deepseek-v3.2',
  'qwen/qwen3.8-max',
  'qwen/qwen3.8-max-free',
  'qwen/qwen3.7-max',
  'qwen/qwen3.5-plus-02-15',
  'qwen/qwen3.5-397b-a17b',
  'qwen/qwen3.5-9b',
  'qwen3.6-flash',
  'nvidia/nemotron-3-nano-omni-30b-a3b-reasoning:free',
  'anthropic/claude-opus-4.8-fast',
  'anthropic/claude-sonnet-4.5',
  'anthropic/claude-fable-5',
  'x-ai/grok-4.20-beta',
  'x-ai/grok-4.6',
  'x-ai/grok-4.5',
  'z-ai/glm-5-turbo',
  'z-ai/glm-5.3-free',
  'z-ai/glm-5.3',
  'z-ai/glm-5.3-flash',
  'moonshotai/kimi-k3',
  'openai/gpt-5.2',
  'openai/gpt-5.4-nano',
  'openai/gpt-5.6-luna',
  'openai/gpt-5.6-terra',
  'google/gemini-3.5-flash-lite',
  'stepfun/step-3.5-flash',
  'MiniMax-M3',
  'miromind/mirothinker-1-7-deepresearch',
];
