// BAI (b.ai) exposes an OpenAI-compatible model-discovery endpoint (GET /v1/models),
// so models are normally registered dynamically at startup. This list is only
// used as a manual fallback when the live /models endpoint is unavailable. It
// mirrors the catalog BAI serves so the provider stays routable.
export const MODELS: string[] = [
  'minimax-m3',
  'minimax-m2.7',
  'glm-5.1',
  'glm-5.2',
  'gpt-5.6-sol',
  'gpt-5.6-terra',
  'gpt-5.6-luna',
  'gpt-5.5',
  'gpt-5.5-instant',
  'gpt-5.4',
  'gpt-5.2',
  'gpt-5.4-pro',
  'gpt-5.4-mini',
  'gpt-5-mini',
  'gpt-5.4-nano',
  'gpt-5-nano',
  'claude-opus-5',
  'claude-fable-5',
  'claude-opus-4.8',
  'claude-opus-4.7',
  'claude-opus-4.6',
  'claude-opus-4.5',
  'claude-sonnet-5',
  'claude-sonnet-4.6',
  'claude-sonnet-4.5',
  'claude-haiku-4.5',
  'gemini-3.1-pro',
  'gemini-3-flash',
  'gemini-3.5-flash-lite',
  'gemini-3.6-flash',
  'kimi-k2.6',
  'glm-5.3',
  'kimi-k3',
  'qwen3.8-max',
  'deepseek-v4-flash',
  'deepseek-v4-pro',
  'gemini-3.5-flash',
  'qwen3.8-27b',
];